/*
 * hwConfig.h
 *
 *  Created on: Jul 10, 2024
 *      Author: dbank
 */

#ifndef INC_HWCONFIG_HWCONFIG_H_
#define INC_HWCONFIG_HWCONFIG_H_

#define FW_VERSION 0.1
#define I2C_STM32_TO_ESP32_ROLE_MASTER
#define ESP32_INTERRUPT_REQUEST_COUNTING_SEMAPHORE_MAX	21

#define PERIPHERY_MENU_TIMEOUT_TASK_DELAY	2000

#endif /* INC_HWCONFIG_HWCONFIG_H_ */
